#+title: 从词的史中看词学赏析与当代词学的继承发展（一）


之前一直想写一点感想，探索“词”的近代化之路，可恨从未动笔，蹉跎至今。

近日现越发觉得科研的不适，便越缺乏勇气，试图逃离，反倒给出了大量的时间做一点关于这个课题的文章，便在仓促之间动了笔。记得前面对《存在与时间》的思路阐述、对“儒学”的梳理都是累土的功，还没弄完便又开了一个完全新的坑，还是十分自责的。

前几日社团里霜花簃使将词的史梳理到了南渡，虽然我多未听他的讲学，但是PPT也累计了不少，我向来没有工夫梳理史，更别提闲暇时候看史了。因此打算趁此机会将冷眠学长的PPT简单整理，作为日后翻阅的备份。其中“看词学赏析的基本问题”一节多是借了学长的骨架记录自己的观点，而后面的“唐五代词”则多是依着那些浓缩的PPT文字删改而成的。

* 刚与柔——俗与雅——婉约与豪放：看词学赏析的基本问题

世间的东西纷繁复杂，多是不能用二元的角度分的，用了便滋生口舌。但是，面对太过复杂的东西，最容易想到的划分思路便也是二元。什么叫赏析？赏析就是一种美学角度上的认识。而认识，常常就从分类开始。时下有一些冠以“人工智能”大名的所谓前沿工作，试图模拟人的思维去认识和改造这个世界。他们目前所作的大部分工作其实很浅，最基本的，他们把“认识”一个东西看作是一个“分类”。似乎如果输入猫的图片可以导出0，狗的图片可以导出1，便能够说明该分类器能够认识到区分猫与狗的一些特质，而这一类的“区分”足够多，我们便在这种认识上产生一种智能了。我们不去思索这种进展的可行性，单单看分类问题里二分类是多么的基本，就知道这种工作对于人类认识事物或“声称了解事物”有多么大的价值。

下面先从词学的角度看看，有哪些基本的分类。

** 刚与柔

刚与柔的划分不是来自于词，从对极早的文学进行赏析时就有这种说法了。刘勰（音协）在《文心雕龙》里曾经写道：“文之任势，势有刚柔。”这个势字用的很妙，今人读李白的《蜀道难》《梦吟别》，再读白居易的《长恨歌》，想必就能对这个势有差不多的体会。势是一种状态，一个瞬间一个瞬间的东西，而非一个过程，今人写小说，拍电影，又给出了一个类似但不完全相同的概念，“节奏”，其实想表达的东西倒有些类似。势毕竟是无形的，而有形的依托便是诸如文字、音声等媒介。这种媒介可以将之看作不同的水，如果是条小溪，可以有急有缓，如果是个大海，自然又能容纳无穷无尽势的变化，因而不同文体的长度，组织的方式，等等，就因此而百花齐放了。此处单捡词的讨论，倘以小令看作小湖，看作短溪，那么长调就有深泽、大河的气魄，如果能将二者事宜起来，相必就会好更多。当然，对“势”的引用还进入了其他的一些地方，比如《棋王》里讲下棋的，这里就不再讨论了。

刚与柔仅仅是一个简单的二元划分，或许是受《周易》符号增殖哲学的影响，偏刚偏柔的诗词被分成了二十四类：雄浑、冲淡、纤秾、沉著、高古、典雅、洗炼、劲健、绮丽、自然、含蓄、豪放、精神、缜密、疏野、清奇、委曲、实境、悲慨、形容、超诣、飘逸、旷达、流动。 看看这二十四类，分的其实参差不齐，有说诗的，有说人的，有说描写对象的,有说描写特点的。正如某人把西方戏剧情节凝聚了几十类一样，对诗的类别分析同样给人一种很无奈的绝望感——至少我怀有这种感觉。所以，个人观点：不要轻易在赏析文学的时候动用太多的统计，因为标签永远只是标签，一个作品可以有无穷多的标签，而其所属的有限多的标签永远无法完全代表一个作品。

** 俗与雅
文学的划分第二个点就是俗与雅。俗与雅是一个很有意思的比对，可惜今日的话语下似乎不太受到关注。易和俗雅之比相混淆的，是文史之分。由于文的东西多让人偏着雅去，而史的东西又离着俗有点近，所以很多人直接把文看作雅了，我觉得不妥。其实俗雅的划分非常简单，因为这是一种直觉上的审美感。举个例子，个人觉得武侠小说里面“青衣青剑”就是很雅的东西，可是如果去玩当代的一些武侠游戏，衣服那么精致，家居那么精致，坐骑那么精致，武功释放那么精致，反而落入了一种新的俗。史的俗似乎是不可避免的，但是又有别有雅味。此处可举“绿蚁新醅酒”为例，绿酒本是最低一等的酒（因杂菌滋生而发绿），却也能因为喝的人的境界而发生改变，这才是真正的对雅俗的分析。在文和史的中庸里达到自我最可接收的幅度，或许这样才能找到自我最可欣赏的作品吧。

上面提及的俗雅的辩在当代文学里更是非常明显，而展现在词学里，一个经典的例子便是柳永。柳永是写俗词的（就好像给当代网红主播写流行歌曲？），但是一生中少有的几篇雅词却留了名（流传的基本上都是雅词）。这说明“人民群众”、“喜闻乐见”这种词，不能随便滥用。李清照曾经评论过柳永：“有柳屯田永者，变旧声作新声，出《乐章集》，大得声称于世；虽协音律，而词语尘下。”

当然，文学作品具有受众仍然十分重要。没有赏析就少有创作，少有创作就少有好作品，而赏析虽然很大程度上催发了劣币，但是这种变异对传世之作的产生仍然不可缺少。这个观点或许在今日的小说界不怎么合理，事实如何只有看时间如何验证了。

** 婉约与豪放

婉约与豪放似乎是词分类里最常用的俩词。我觉得这两个词隐隐将词分成了心情上的积极与消极两派。但是，诡异之处在于，从未有人将唐诗分成豪放与婉约，没有吧？没有人这么干吧？唐诗里有边塞，有的写的也很豪放但没人这么说，唐诗里有送别有闺怨，但是也没人怎么怎么就说了。唐诗分类分的五花八门，为什么到了词就变了呢？难道是因为词写的主要就这两类不成？ 个人觉得不是如此，但是只不过个别词人的风格太深（时代背景），因而留下了较硬的刻痕罢了。

下面给出一些关于这个问题的讨论：

词体大略有二：一体婉约，一体豪放。婉约者欲其词情蕴藉，豪放者欲其气象恢宏。盖亦存乎其人，如秦少游之作多是婉约，苏子瞻之作多是豪放。大抵以婉约为正，故东坡称少游为今之词手，后山评东坡如教坊雷大使舞，虽极天下之工，要非本色。——《诗余图谱》

近来有些词论家把宋词分为婉约与豪放两派，而以苏轼为后者的领袖。这样评价宋词和苏轼，是否符合历史实情?……这是一个宋代文学史上的重大问题。这是在解放以前即有人谈起，而解放以后越谈越起劲，越谈越肯定的问题。由此而推演发挥，则豪放一派变为中国词史上的主流或进步或革新的力量，思想性、艺术性、文学价值最高；而婉约派则是保守力量，消极成分，落后乃至庸俗不堪，不值得赞扬提倡，必须加以批判等等。于是不谈词则已，一谈则言必称苏、辛，论必批柳、周。……（《吴世昌《有关苏词的若干问题》）

** 其他角度
词学的赏析还有人看“正与变”（不懂，不做评论）。甚至还有按地区、时代、群落、集团去划分，这种划分有其合理之处，比如鱼类的动物多会游泳，如果我们发现了一个动物是鱼类（或拥有鳃之类的结构），那么我们估测它在习性上有会游泳这一点。但是，根本上，正如我们在对生物学中功能的思考不能局限在基因的划分一样（比如鲸鱼拥有和鱼类很不同的基因，但是也有游泳的能力），我们应该同样的，在文学赏析上，用展现风格、描写内容的相似性去思考陌生作者、作品的特点。地区、时代、群落都是十分值得去借鉴的东西，他们有助于也是仅仅辅助我们解读文本。

至于现象学、诠释学、符号等新的解读方式，我觉得还是不写了吧。


* 词的诞生：唐早中期、花间词与南唐词人群

啊，看到这个标题名，就知道我又偷了懒。我直接按照最偷懒的方式（时间，空间，本质上是词人）对词进行划分了。这违背了上一小节里提出的“依词本身放矢”的口号，可我实在是太懒了，懒到甚至这一小节剩下的东西全都是我复制粘贴的。哎。

** 词的兴起，诗的渐衰——文字与音乐的第三次合作
第一次合作是先秦时代《诗经》与雅乐，第二次是乐府与清乐、胡乐的结合。之后就出现了曲子词，在民间流行之后变成了民俗歌曲一般的民间乐。比如《渔歌子》《忆江南》，这些东西最后被士大夫看上了，加以改造，形成了词。词的兴起还有一个原因是诗发展达到了一种瓶颈，很难再在形式上、格律上取得更大的突破（我暂时还不能理解这个说法）。一般认为词在某些地方比诗具有一定的优势。

总之，词就这样发展起来了。
** 唐早期词
*** 李白

 菩萨蛮·平林漠漠烟如织
 平林漠漠烟如织，寒山一带伤心碧。暝色入高楼，有人楼上愁。
 玉阶空伫立，宿鸟归飞急。何处是归程？长亭连短亭。

此首望远怀人之词，寓情于境界之中。一起写平林寒山境界，苍茫悲壮。……然其写日暮景色，更觉凄黯。此两句，自内而外。“瞑色”两句，自外而内。烟如织、伤心碧，皆瞑色也。两句折到楼与人，逼出“愁”字，唤醒全篇。所以觉寒山伤心者，以愁之故；所以愁者，则以人不归耳。下片，点明“归”字。“空”字，亦从“愁”字来。乌归飞急，写出空间动态，写出鸟之心情。鸟归人不归，故云此首望远怀人之词，寓情于境界之中。一起写平林寒山境界，苍茫悲壮。粱元帝赋云“空伫立”。“何处”两句，自相呼应，仍以境界结束。但见归程，不见归人，语意含蓄不尽。（唐圭璋《唐宋词简释》）


忆秦娥·箫声咽
箫声咽，秦娥梦断秦楼月。秦楼月。年年柳色，灞陵伤别。
乐游原上清秋节，咸阳古道音尘绝。音尘绝。西风残照，汉家陵阙。

此词自抒积感，借闺怨以写之，因身在秦地，即以秦女箫声为喻。起笔有飘飘凌云之气。以下接写离情，灞桥折柳，为迁客征人伤怀之处……下阕仍就秦地而言，乐游原上，当清秋游赏之时，而古道咸阳，乃音尘断绝，悲愉之不同如是。古道徘徊，即所思不见，而所见者，惟汉代之遗陵废阙，留残状于西风夕照中。一代帝王，结局不过如是，则一身之伤离感旧，洵命之衰耳。结二句俯仰今古，如闻变徵之音。（俞陛云《唐五代两宋词选释》）

立一向之西风，沐满川之落照，而入我目者，独有汉家陵阙，苍苍莽莽，巍然而在。当此之际，乃觉凝时空于一点，混悲欢于百端，由秦娥一人一时之情，骤然升华而为吾国千秋万古之心。盖自秦汉以逮隋唐，山河缔造，此地之崇陵，已非复帝王个人之葬所，乃民族全体之碑记也。良人不归，汉陵长在。（周汝昌《千秋一寸心——周汝昌讲唐诗宋词》）

西风二句表现的思想感情不是仅仅悲征戍、怀远人的妇女所能有的，不是一般思念丈夫的妻子所能有的。 （安旗《李白词二首之我见》）
*** 张志和

渔歌子
西塞山前白鹭飞，桃花流水鳜鱼肥。青箬笠，绿蓑衣，斜风细雨不须归。

自来高洁之士，每托志渔翁，访尚父于硒溪，讽灵钧于湘浦，沿及后贤，见于载籍者夥矣。而轩冕之士，能身在江湖者，实无几人。志和固手把钓竿者，而词言‘西塞’、‘巴陵’、‘松江’、‘雷溪’、‘钓台’，地兼楚越，非一舟能达，则此词亦托想之语，初非躬历。然观其每首结句，君子固穷，达人知命，襟怀之超逸可知。‘桃花流水’句，犹世所传诵。（俞陛云《唐五代两宋词选释》）
*** 刘禹锡

竹枝
山桃红花满上头，蜀江春水拍山流。花红易衰似郎意，水流无限似侬愁。

四方之歌，异音而同乐。岁正月，余来建平，里中儿联歌《竹枝》，吹短笛，击鼓以赴节。歌者扬袂睢舞，以曲多为贤。聆其音，中黄钟之羽，其卒章激讦如吴声，虽伧佇不可分，而含思宛转，有淇、濮之艳。昔屈原居湘、沅间，其民迎神，词多鄙陋，乃为作《九歌》，到于今荆楚鼓舞之。故余亦作《竹枝词》九篇，俾善歌者飏之，附于末，后之聆巴歈，知变风之自焉。（《竹枝词序》）
*** 白居易
忆江南
江南好，风景旧曾谙。日出江花红胜火，春来江水绿如蓝。能不忆江南？
江南忆，最忆是杭州。山寺月中寻桂子，郡亭枕上看潮头。何日更重游？
江南忆，其次忆吴宫。吴酒一杯春竹叶，吴娃双舞醉芙蓉。早晚复相逢？

较宋词自然有身分。（沈际飞《草堂诗余别集》）

诗馀上乘。（近藤元粹《白乐天诗集》）
** 花间词派

花间词派，顾名思义，是歌舞享乐、流连花间的词的流派。《花间词》是后蜀赵崇祚选编，收录温庭筠、皇甫松、孙光宪、韦庄、和凝、薛昭蕴、牛峤、张泌、毛文锡、牛希济、欧阳炯、顾夐、魏承班、鹿虔扆、阎选、尹鹗、毛熙震、李珣18人，共500首词。由欧阳炯作叙。花间词源头在晚唐，以五代词、西蜀词为主，鼻祖是温庭筠、侧艳，传播者是由中原入蜀的唐末文人韦庄，继承主力是生长在蜀中的文人。

花间词的特点是：
1. 专写小令；
2. 题材以相思怨别为主；
3. 词风倾向于阴柔婉约；
4. 认为“词为艳科”。

下摘录几位作者的词以示说明。
*** 温庭筠
菩萨蛮（其一）
小山重叠金明灭，鬓云欲度香腮雪。懒起画蛾眉，弄妆梳洗迟。
照花前后镜，花面交相映。新帖绣罗襦，双双金鹧鸪。

此首写闺怨，章法极密，层次极清。首句，写绣屏掩映，可见环境之富丽；次句，写鬓丝撩乱，可见人未起之容仪。三、四两句叙事，画眉梳洗，皆事也。然“懒”字、“迟”字，又兼写人之情态。“照花”两句承上，言梳洗停当，簪花为饰，愈增艳丽。末句，言更换新绣之罗衣，忽见衣上有鹧鸪双双，遂兴孤独之哀与膏沐谁容之感。有此收束，振起全篇。上文之所以懒画眉、迟梳洗者，皆因有此一段怨情蕴蓄于中也。（唐圭璋《唐宋词简释》）

此感士不遇之作也。篇法仿佛《长门赋》，而用节节逆叙。此章从梦晓后领起，“懒起”二字，含后文情事。“照花”四句，《离骚》初服之意。（张惠言《词选》）

固哉，皋文之为词也！飞卿《菩萨蛮》、永叔《蝶恋花》、子瞻《卜算子》，皆兴到之作，有何命意？皆被皋文深文罗织。（王国维《人间词话》）
这首《菩萨蛮》不仅称物芳美，也具有“其文约，其词微”的特点，富有暗示性，容易使人产生种种联想。（张燕瑾《唐宋词选析》）

菩萨蛮（其二）
水精帘里颇黎枕，暖香惹梦鸳鸯锦。江上柳如烟，雁飞残月天。
藕丝秋色浅，人胜参差剪。双鬓隔香红，玉钗头上风。

王右丞诗：“杨花惹暮春。”李长吉诗：“古竹老梢惹碧云。”温庭筠词：“暖香惹梦鸳鸯锦。”孙光宪词：“六宫眉黛惹春愁。”用“惹”字凡四，皆绝妙。（杨慎《升庵诗话》）
飞卿词极流利，为《花间集》之冠。《菩萨蛮》十四首，尤为精湛之作。兹从《花庵词选》录四首以见其概。十四首言及杨柳者凡七，皆托诸梦境。风诗托兴，屡言杨柳，后之送客者，攀条赠别，辄离思黯然，故词中言之，低回不尽，其托于梦境者，寄其幽渺之思也。(俞陛云《唐五代两宋词选释》)
江上以下，略叙梦境。（张惠言《词选》）
帘内之清秾如斯，江上之芊绵如彼。千载之家，无论识与不识，解与不解，都知是好言语矣。（俞平伯《读词偶得》）
*** 韦庄

菩萨蛮 五首
    红楼别夜堪惆怅，香灯半卷流苏帐。残月出门时，美人和泪辞。    琵琶金翠羽，弦上黄莺语。劝我早归家，绿窗人似花。（其一）
    人人尽说江南好，游人只合江南老。春水碧于天，画船听雨眠。    垆边人似月，皓腕凝霜雪。未老莫还乡，还乡须断肠。（其二）


追忆当年离别之词。起言别夜之情景，次言天明之分别。换头承上，写美人琵琶之妙。末两句，记美人别时言语。前事历历，思之惨痛，而欲归之心，亦愈迫切。韦词清秀绝伦，与温词之浓艳者不同，然各极其妙。(唐圭璋《唐宋词简释》)
深情苦调，意婉词直，屈子《九章》之遗。（陈廷焯《词则·大雅集》）

此首写江南之佳丽，但有思归之意。起两句，自为呼应。人人既尽说江南之好，劝我久住，我亦可以老于此间也。“只合”二字，无限凄怆，意谓天下丧乱，游人飘泊，虽有乡不得还，虽有家不得归，惟有羁滞江南，以待终老。“春水”两句，极写江南景色之丽。“垆边”两句，极写江南人物之美。皆从一己之经历，证明江南果然是好也。“未老”句陡转，谓江南纵好，我仍思还乡，但今日若还乡，目击离乱，只令人断肠，故惟有暂不还乡，以待时定。情意宛转，哀伤之至。（唐圭璋《唐宋词简释》）

如今却忆江南乐，当时年少春衫薄。骑马倚斜桥，满楼红袖招。    翠屏金屈曲，醉入花丛宿。此度见花枝，白头誓不归。（其三）
    劝君今夜须沉醉，樽前莫话明朝事。珍重主人心，酒深情亦深。    须愁春漏短，莫诉金杯满。遇酒且呵呵，人生能几何。（其四）
    洛阳城里春光好，洛阳才子他乡老。柳暗魏王堤，此时心转迷。    桃花春水渌，水上鸳鸯浴。凝恨对残晖，忆君君不知。（其五）

“未老莫还乡”，犹冀老而还乡也。其后朱温篡成，中原愈乱，遂决劝进之志。故曰“如今却忆江南乐”，又曰“白头誓不归”，则此词之作，其在相蜀时乎！（张惠言《词选》）
端己此二首自是佳词，其妙处如芙蓉出水，自然秀艳。按韦曾二度至江南，此或在中和时作，与入蜀后无关，张氏《词选》好为附会，其言不足据也。（李冰若《栩庄漫记》）
韦庄在如此短的一首小令中，竟然用了两个“须”字，两个“莫”字，口吻的重叠成为这首词的特色所在，也是佳处所在。下面写“遇酒且呵呵，人生能几何”，又表现得冷漠空泛。（叶嘉莹《唐宋词十七讲》）
此首忆洛阳之词，身在江南，还乡固不能，即洛阳亦不得去，回忆洛阳之乐，不禁心迷矣。起两句，述人在他乡，回忆洛阳春光之好。“柳暗”句，又说到眼前景色，使人心恻。末句，对景怀人，朴厚沉郁。（唐圭璋《唐宋词简释》）
此章致思唐之意。（张惠言《词选》）
韦端己《菩萨蛮》四章惓惓故国之思，而意婉词直，一变飞卿面目，然消息正自相通。（陈廷焯《白雨斋词话》）
*** 孙光宪

浣溪沙（其一）
蓼岸风多橘柚香，江边一望楚天长，片帆烟际闪孤光。
目送征鸿飞杳杳，思随流水去茫茫，兰红波碧忆潇湘。

“片帆”七字，压遍古今词人。”
“闪孤光”三字警绝，无一字不秀炼，绝唱也。”（陈廷焯《云韶集》）
昔黄玉林赏其“一庭疏雨湿春愁”为古今佳句，余以为不若“片帆烟际闪孤光”，尤有境界也。（王国维《人间词话附录》）
昔在湘江泛舟，澄波一碧，映似遥山，时见点点白帆，明灭于夕阳烟霭间，风景绝胜。词中“帆闪孤光”句足以状之。“兰红波碧”殊令人回忆潇湘也。（俞陛云《五代词选释》）
“片帆”句妙矣。“兰红波碧”四字，惟潇湘足以当之，他处移用不得，可谓善于设色。（李冰若《栩庄漫记》）
*** 李询
南乡子
乘彩舫，过莲塘，棹歌惊起睡鸳鸯。游女带花偎伴笑，争窈窕，竞折团荷遮晚照。

咏南荒风景，惟李珣《南乡子》词有17首之多。荔子轻红，桄榔深碧，猩啼暮雨，象渡瘴溪，更萦以艳情，为词家特开新采。（俞陛云《唐五代两宋词选释》）
绝无曲折，却极形容之妙。（况周颐《蕙风词话》）
李珣、欧阳炯辈，俱蜀人。各制《南乡子》数首，以志风土。亦《竹枝》体也。（周密《齐东野语》）

河传
去去！何处？迢迢巴楚，山水相连。朝云暮雨，依旧十二峰前，猿声到客船。
愁肠岂异丁香结？因离别，故国音书绝。想佳人花下，对明月春风，恨应同。

一气舒卷,若断若连，有水流花放之乐，结得温厚。（陈廷焯《白雨斋词话》）
李德润《河传》云: “想佳人花下，对明月春风，恨应同”，高竹屋《齐天乐·中秋夜怀梅溪》云: “古驿烟零, 幽垣梦冷, 应念秦楼十二”，两家用意略同。高词伤格不可学, 李词则否, 其故当细思之”。（况周颐《餐樱庑词话》）
*** 花间词的标准与范式

1. “诗庄词媚”：

作诗遵从儒家诗教观念；注重社会功能，政治宣教；“诗言志”；“兴、观、群、怨”
填词抒发儿女闺阁之情；女性形象；要眇宜修；“小道”“侧艳”
词出诗外，源头虽若“滥觞”，本亦有发展为长江大河的可能，像诗一样的浩瀚，而自《花间》以后，大都类似清溪曲涧，虽未尝没有曲折幽雅的小景动人流连，而壮阔的波涛终感其不足。在文学史上，词便成为诗之余，不管为五、七言之余也罢，三百篇之余也罢，反正只是“余”。（俞平伯《唐宋词选释》）

2. “词为艳科”：

爱情题材从诗到词的“迁移”，导致了诗与词的“分野”；“侧艳”的词风左右了词的创作方向，形成了“真、艳、深、婉、美”的风格特点。

3. 花间范式——文人的审美情思
+ 这种情感往往不是创作主体自我独特的人生体验，不是从他自身的生活境遇和经历中提炼出来的情思，而是世代重复的、人皆有之的离愁别绪、男欢女爱。
+ 创作主体不是以自我的身份宣泄郁闷，吐露心声，而是以“非我”的身份，假托他人的声态口吻来言情抒感。
+ 词的抒情主人公多是无定指、无人称甚至难分性别的人。创作主体的自我形象、人格精神、性情怀抱都隐而不露，或是根本就不存其中。
+ 花间词之所以形成这种类型化、非我化的抒情范式，是决定于他们的创作环境、创作观念和创作目的的。
** 多愁善感的南唐词
*** 冯延巳

鹊踏枝
谁道闲情抛掷久。每到春来，惆怅还依旧。日日花前常病酒，不辞镜里朱颜瘦。
河畔青芜堤上柳。为问新愁，何事年年有？独立小桥风满袖，平林新月人归后。

可谓沉着痛快之极，然却是从沉郁顿挫来，浅人何足知之。（陈廷焯《白雨斋词话》）
《蝶恋花》诸作，情词悱恻，可群可怨。张皋文云：“忠爱缠绵，宛然《骚》《辩》之义。”余最爱诵之。如“日日花前常病酒。不辞镜里朱颜 瘦。”……思深意苦，又复忠厚恻怛。词至此则一切叫嚣纤冶之失自无从犯其笔端矣。（吴梅《词学通论》）
此首写闺情，如行云流水，不染纤尘。起两句，自设问答，已见凄婉。“日日”两句，从“惆怅”来，日日病酒，不辞消瘦，意更深厚。换头，因见芳草、杨柳，又起新愁。问何以年年有愁，亦是恨极之语。末两句，只写一美境，而愁自寓焉。（唐圭璋《唐宋词简释》）

鹊踏枝
梅落繁枝千万片。犹自多情，学雪随风转。昨夜笙歌容易散，酒醒添得愁无限。
楼上春山寒四面。过尽征鸿，暮景烟深浅。一晌凭栏人不见，鲛绡掩泪思量遍。

上阕热闹起，歌散酒醒收。写出了有情生命所面对的无常之际的缱绻哀伤，此为人世千古的共同悲哀。下阕写主人孤独地处身四面暮寒，思量不已。鲛绡掩泪，表现了一种幽微珍美的悲苦情意。（张自文《冯延巳词研究》）
诗词原可观人品，而亦不尽然。（略）冯正中《蝶恋花》四章，忠爱缠绵，已臻绝顶，然其人亦殊无足取，尚何疑于史梅溪耶？诗词不尽能定人品，信矣。（陈廷焯《白雨斋词话》）
词有貌不深而意深者，韦端己《菩萨蛮》、冯正中《蝶恋花》是也。（陈廷焯《白雨斋词话》）
正中身仕偏朝，知时不可为，所为《踏鹊枝》诸阕，幽咽惝恍，如醉如迷，此皆贤人君子不得志发愤之所作也。（沈曾植《曼陀罗寱词》）
*** 李璟
摊破浣溪沙
菡萏香销翠叶残，西风愁起绿波间。还与韶光共憔悴，不堪看。
细雨梦回鸡塞远，小楼吹彻玉笙寒。多少泪珠何限恨，倚阑干。

“菡萏香销翠叶残，西风愁起绿波间”大有众芳芜秽，美人迟暮之感，乃古今独赏其“细雨梦回鸡塞远，小楼吹彻玉笙寒”，故知解人正不易得。（王国维《人间词话》）
南唐中主《出花子》云：“还与韶光共憔悴，不堪看。”沉之至，郁之至，凄然欲绝。后主虽善言情，卒不能出其右之。（陈廷焯《白雨斋词话》）
按“细雨梦回”二句，意兴清幽，自系名句。 结尾“倚阑干”三字，亦有说不尽之意。（陈廷焯《白雨斋词话》）
此词之佳，在于沉郁。夫“菡萏香销”、“西风愁起”与“韶光”无涉也，而在伤心人见之，则夏景繁盛亦易残，与春光同此憔悴耳。故一则曰“不堪看”，一则曰“何限恨”，其顿挫空灵处，全在情景融拾，不事雕琢，凄然欲绝。至“细雨”、“小楼”二语，为“西风愁起”之点染语，炼词虽工，非一篇之至胜处。而世人竞赏此二语，亦可谓不善读者矣。（吴梅《词学通论》）

玉楼春
晚妆初了明肌雪，春殿嫔娥鱼贯列。笙箫吹断水云间，重按霓裳歌遍彻。
临风谁更飘香屑，醉拍阑干情味切。归时休放烛花红，待踏马蹄清夜月。

豪宕。（谭献《复堂词话》）
此在南唐全盛时所作。按霓羽之清歌，爇沉香之甲煎，归时复踏月清游，洵风雅自喜者。此词极富贵，而《浪淘沙令》“流水落花春去也，天上人间”，又极凄婉，则富贵亦一场春梦耳。(略)其“清夜月”结句，极清超之致。《艺苑卮言》云:“后主直是词手。”（俞陛云《唐五代两宋词选释》）
此首亦写江南盛时景象，起叙嫔娥之美与嫔娥之众。次叙春殿歌舞之盛，下片，更叙殿中香气氤氲与人之陶醉。“归时”两句，转出踏月之意。想见后主风流豪迈之襟抱，与“花间”之局促房栊者，固自有别也。（唐圭璋《唐宋词简释》）
*** 李煜

虞美人
春花秋月何时了？往事知多少。小楼昨夜又东风，故国不堪回首月明中。
雕栏玉砌应犹在，只是朱颜改。问君能有几多愁？恰似一江春水向东流。

一声恸歌，如闻哀猿，呜咽缠绵，满纸血泪。（陈廷悼《云韶集》）
李后主原是天才之文学家，又是亡国之君，此三首（指《浪淘沙》两首与《虞美人》)乃国破之后，在汁梁作寓公时所作，蜷怀故国，又不敢明白表示，忍泪吞声，亦不能自抑，而流露于言辞。闻宋太祖赐以牵机药，亦因见此词。（梁启勋《词学》）
此首感怀故国，悲愤已极。起句，追维往事，痛不欲生！ 满腔恨血，喷薄而出：诚《天问》之遗也。“小楼”句承起句，缩笔吞咽；“故国”句 承起句，放笔呼号。一“又”字惨甚。 东风又入，可见春花秋月一时尚不得遽了。罪孽未满，苦痛未尽，仍须偷息人间， 历尽磨折。下片承上，从故国月明想入，揭出物是人非之意。末以问答语，吐露心中万 斛愁恨，令人不堪卒读。通首一气盘旋，曲折动荡，如怨如慕，如泣如诉。（唐圭璋《唐宋词简释》)


相见欢
林花谢了春红，太匆匆。无奈朝来寒雨晚来风。
胭脂泪，相留醉，几时重。自是人生长恨水长东。

濡染大笔。（谭献《词辨》）
此首伤别，从惜花写起。“太匆匆”三字，极传惊叹之神，“无奈”句，又转怨恨之情，说出林花所以速谢之故，朝是雨打，晚是风吹，花何以堪，人何以堪。说花即以说人，语固双关也。“无奈”二字，且见无力护花，无计回天之意。一片珍惜怜爱之情，跃然纸上。下片，明点人事，以花落之易，触及人别离之易。花不得重上故枝，人亦不易重逢也。“几时重”三字轻顿；“自是”句重落。以水之必然长东，喻人之必然长恨，语最深刻。“自是”二字，尤能揭出人生苦闷之义蕴，与“此外不堪行”，“肠断更无疑”诸语，皆重笔收来，沉哀人骨。（唐圭璋《唐宋词简释》）
*** 南唐对花间范式的新变

共同点：“感发之意趣”
不同点：
（正中）沉挚顿挫、伊郁惝恍之情致，有分量有深度；
（中主）多情与锐感之心偶然体悟到的极为自然却极具感发之力的心灵触动；
（后主）以真纯任纵之笔写其官能感知、情事感动乃至家国悲痛，体悟到人世的无常。

冯延巳词向着类型性的士大夫化转变，那么李煜词朝着个体化、自我化的方向拓展（变伶工之词为士大夫之词）；
将男性士大夫的情绪、体验写人词中，标志着五代词的内质由女性化向着男性士大夫化又迈进了一步，只是这种男性化常被裹在女性化的外衣下；
创作主体与词作文本中的“我”逐渐具有同一对应的关系，词日渐由非我化走向自我化，由类型化走向个体化；
* 对唐五代诗的总结总结
还是复制粘贴：

+ 词以境界为最上。有境界则自成高格，自有名句。五代北宋之词所以独绝者在此。
+ 张皋文谓飞卿之词“深美闳约”，余谓此四字唯冯正中足以当之。刘融斋（刘熙载）谓“飞卿精艳绝人”，差近之耳。
+ 端己词情深语秀，虽规模不及后主、正中，要在飞卿之上。观昔人颜、谢优劣论可知矣。
+ “画屏金鹧鸪”，飞卿语也，其词品似之。“弦上黄莺语”，端己语也，其词品亦似之。正中词品，若欲于其词句中求之，则“和泪试严妆”殆近之欤！
+ 温韦之精绝所以不如正中者意境有深浅也。
+ 王嫱、西施，天下美妇人也，严妆佳，淡妆佳，粗服乱头不掩国色。飞卿严妆也，端己淡妆也。后主则粗服乱头矣。
+ 词至李后主而眼界始大，感慨遂深，遂变伶工之词而为士大夫之词。周介存置诸温韦之下，可为颠倒黑白矣。“自是人生长恨水长东”、“流水落花春去也，天上人间”，《金荃》《浣花》，能有此气象耶？
+ 尼采谓:“一切文学，余爱以血书者。”后主之词，真所谓以血书者也。宋道君皇帝《燕山亭》词亦略似之。然道君不过自道身世之戚，后主则俨有释迦、基督担荷人类罪恶之意，其大小固不同矣。


叶嘉莹《迦陵论词丛稿：从〈人间词话〉看温韦冯李四家词的风格——兼论晚唐五代时期词在意境方面的拓展》
