小论古代经卷篇

* 引言——从一件身边的小事开始
前两天我进行本科毕业设计答辩，本以为通过这种答辩是一桩不值一提的小事，可没想到在答辩中成功和一个老教授争执起来，把短短三分钟的提问环节直接扩展到了一刻钟，甚至还差点二辩。
在这件事里分析谁对谁错实在是没有意义，毕竟定义“对”与“错”的标准都可以找出许多。他认为我过于狂妄，因为“一个本科生怎么能做出的算法效果这么好呢？”，我觉得他带有成见，带有一种做工程的人常用的对理论或算法研究者根深蒂固的成见。我的一些旁听的同学说我惨，遇到这种令人无奈的情况。但是，他们再怎么站在我这边，“答辩的那么多学生里，仅仅有我和这位老师对线了”这个事实却是无可指摘。我从这件事中意识到自己人身生活里的一些问题，并想通过这件无波无澜的小事谈一谈最近读书的另一些感受。
首先，这件事从某种意义上可以怪在我的头上，也可以说，问题在我。这不是指我所讲自己毕设内容的问题（没有任何问题），也不是我回答老教授问题时的问题（这些回答本身没有问题）。这个问题完全是情境问题，也就是场合问题。答辩从来不是学术交流的过程（正如很多学术报告也不是学术交流一样），如果一个人单纯从术业知识的角度阐发，无论怎么和其他人进行解释、沟通，都无法获得成功，因为答辩本身就不是为了看你是否掌握了这些知识。当你动口去讲述你的毕设工作，内行的自然就明白你的水平了，而外行的人，便从中不再去关注你的水平。所以他们问出的问题，不是你要回答的问题，而是他们想要你回答的问题。在答辩的场合里，当一个老教授提出很多问题、并带着这样一种语气来来问我，如果我能提前看透：啊，这个人不是在问我问题，而是为了杀一杀他眼中“我狂妄的语气”，让“我的工作”显得“一般般而已”，那么我只需要提前认错，多谈一谈自己的不足之处，提问环节便显而易见地过去了。而我是怎么做的呢？我成了一个愣头青，成了和最亲近的导师、一起交流问题的同学出现的那种交流的过程，就是那种唯识的、唯知识的、对事不对人的讨论，完全停留在知识上，那不就彻底完蛋了。教授说：“你说你这个你这个仅仅适用于同构图，而现实场景中哪里有那么多同构图呢？所以你这个算法本身应用面就有问题，是一种无法实际应用的算法。”我本应回答“是这样的，多谢老师提醒，我应该思考如何把这个算法迁移到更广阔的问题上”作为让他消气的方式，可我却回答“目前大多数基于图的研究都是在同构上的，并且我这个算法其实并不要求一定是同构，迁移起来很容易”，这不就犯了大忌！我仍然在争论，一争论我就彻彻底底错了。通过十六分钟的讨论，我看似维持了自己算法的无懈可击，可是这之后，老师便直言我的性格问题了。这完全没错，我的性格就是有问题，不然我就不会蠢到和他对线，尽管我用了再多的“您”这类的敬语，只要我在探讨问题，我就错了。
上述描述或许看起来很“贼”，但是，从道义的角度，我并没违背什么道义，并且严苛一些讲我的算法确实是一个无法实际使用效果垃圾并且很水的东西。从这个角度看，我学到的一课就是，我不会同人打交道。不会和别人打交道的内在含义就是，我不了解什么场合应该怎么做。答辩，对于一个老教授的提问，我能通过回应让人觉得“老教授的观点有问题”吗？尤其在那么多的老师一起的情况下，这是绝对不行的。在这种场合，我只有卑微，因为众多人中只有我自己的面子是最不是面子的面子，更何况损己本身就是一种美德。
第二点就是，我在看见祸事之后的心态，过分的不稳重。常人应该是：出了事，应当如何补救。可是我一开始还在情绪的圈子里，后来在导师的提醒下，才开始想办法补救。自己写了一封信给那位老师道了歉，请指导老师帮忙，这才稍稍显得有了些作用。每次思忖到自己的这些问题，就不得不期望自己将来多多改正。

* TODO 先儒的道
我就是从这个时候开始决定，要读一些经的。
我对读经本身完全没有兴趣，同时我也很讨厌这一类道德说教。道德说教是一种很腻的东西，腻的意思就是：听多了就烦。但是不看不行啊，祸都惹到家门口，都危及毕业了，再不好好学一学怎么做人，岂不是前功尽弃。说起道德，我先想起的当然是儒家，谈儒想起的当然是四书五经，论四书五经打头的当然是论语。绕了一大圈子，就又绕到论语上面了。
此处先引用一段话作为方法论。

一、此学不是零碎断片的知识，是有体系的，不可当成杂货；
二、此学不是陈旧呆板的物事，是活泼泼的，不可目为骨董；
三、此学不是勉强安排出来的道理，是自然流出的，不可同於机械；
四、此学不是凭藉外缘的產物，是自心本具的，不可视为分外。
由明於第一点，应知 道本一贯，故当见其全体，不可守於一曲；
由明於第二点，应知妙用无方，故当温故知新，不可食古不化；
由明於第三点，应知法象本然，故当如量而说，不可私意造作。穿凿附会；
由明於第四点，应知性德具足，故当内向体究，不可徇物忘己，向外驰求。

这段话不仅仅单讲儒学，道释均循之。第一点误解由来已久，毕竟先秦诸子之说多为记段体，段与段之间无明显逻辑关联，因而很容易给人“零碎”之感。可零碎正是因为道过于活，无法束缚身躯，因而言语散乱，甚至貌似前后逻辑颠倒，这是不同时局不同处境的反映罢了。因而，对《诸子》尤要烂熟于心，渗透到四肢百骸，才能品尝到儒的体系知识，以免成为迂腐的人。第二点同样有理，除了前言所述的道理之外，尤其体现在诸子的叙事方式上，诸子从不是法规守则性质的条文，而是例子与阐发的结合。其讨论的话题是人类永恒的话题，未有过时的道理。第三点，自然之意，在于“对人情人欲人理”的洞察与“对社会中人的关系与交往的经验融合”，在这二者基础上，形成的“道理”，自然就是有益于生活的。第四点不由多说。

下面单来看一看《论语》，张汝伦对其曾经有如下评价：“这是一部很容易被人认为是卑之无甚高论的书。像黑格尔就认为里面除了一些善良的、老练的道德教训外，学不到什么特殊的东西。这部书吸引我的地方，就在于它表面看上去容易，真能消受它不容易。一旦领悟后，会觉得夫子为人为学的境界的确非常人所及。这部书对人的启发是无尽的。”

本次粗读《论语》，对我的影响很大，我想就《论语》中包含的以下几点进行讨论。
** 儒家的人生观
*** 何为人？



谈论孔子眼中人的社会性，并与之对比给出其于西方哲学家之人的社会性的关系
*** 何为君子？
*** 何为学？
谈论学的重要性
*** 大同--从社会分工的角度论“君子不器”
孔子的另外一个比较有意思的想法是“君子不器”。这种“不器”的想法背后的哲学



谈论具有“独当一面”能力的人与“不器”之人二者的区别与联系
** 儒家的价值观
*** 仁的意义

*** 道的意义

*** 礼的意义

*** 勇的意义


** 儒家的社会观

*** 从殷商到周的社会制度考

*** 知易行难的问题

*** 儒家的治世之学究竟是不是好的制度？

*** 尊古的好与坏

** 修身的敞亮性






