#+title: 量化投资基本计划书
#+author: 梁子
#+date: <2020-07-22 周三>
#+latex_class: elegentpaper

* 计划书基本内容介绍

** 量化投资中对“量化”这一字眼的诠释
量化投资是投资市场中的一种，其宗旨是通过对投资市场中的各类变量进行“数值化”分析来代替过去的“直觉性”。在这种角度下，量化投资的重点在于如何将各类数值等非直觉的东西通过运算给出一个“合理”的结果。这种结果上的合理主要被定义为两部分：
 1. 收益性。即通过这种方式得出的结论可以实实在在使得投资获得局部的、最优的结果。
 2. 可解释性。量化的方式必须具有一定的可解释性，因为收益总不是可以保证的，而可解释性在任何时刻都可以稀释收益带来的风险。

以后的所有的量化投资的工作都是基于这两点进行的。

** 量化投资的对象
迄今为止，量化投资主要面临这类投资：风险大，收益高。风险大的另一层面的意义是：可操作性强。收益高的另一层面的意义是：值得进行分析。目前而言，这类投资是在股票交易上进行的。股票是一种严格资本化的东西，这类东西操作的空间很大，以致于人们很难精细地做出一个判断，这就给量化投资带来了可行的空间。除此之外，比特币等东西有必要进行吗？还存不存在其他非零和博弈的东西呢？这些问题都有待于寻求一个更加细致的回答。

** 量化投资的目标
目标很简单，就是“赚钱”。关键是：怎么去赚？如何保证自己不是在亏钱？等等问题都有待于解释。因此，当面对量化投资的目标这个问题时，我们应该走得更远一些，要懂得在每一次失败中吸取教训，就像在每一次成功中获得经验一样。在本计划书中，赚钱的目标被分解为下面三个基本的模板：
+ 构筑出一套完整的、全面的、可重复运行的机器（机制、体制）。
  - 这套机器必须是完整的。也就是说：必须构造出一个完整的流程链条：资金的流入流出，数据的采集、处理、决策，后端的计算、前端的展示。我们需要这一整套的链条；
  - 这套机器必须是全面的。也就是说：必须考虑到所有的可能会影响到目标值波动的变量，并把他们都纳入到这套机器里面；
  - 这套机器必须是可重复运行的。也就是说：必须保证这套机器的自适应性，以及普适性。它确实有能力面对好所有的突发局面，无论是积极的还是消极的；
  - 这套机器不必是全自动化的。也就是说：当技术条件等原因还无法良好的对一些自变量进行建模时，我们不能苛求机器的全部智能，而应该适当地融入人的智能进入里面。
+ 在一定的时间内模拟进行投资，并盈利。我们通过各种数据窗口获取未经处理的raw data，之后进行清洗等各种操作最终得到确定的一些结果之后，我们就应该开始进行模拟投资，这种模拟投资指假装自己投入了一些金钱，然后计算在一定时间内所能取得的收益如何。
+ 进行真实投资，并盈利。

* 效果预期——结果预期——工作量预期
我们预期可以得到以下的结果：
** 数据采集与处理端效果预期
必须找到合理的数据采集源，然后处理成 *时序的特征向量* 的形式进行使用。

** 智能计算效果预期
包括：
1. 曲线拟合；
2. 情感分析；
3. 舆情警告；

三个基本部分。

** 前端展示效果预期

目前计划采用javascript写一个前端，然后通过自制APP、自制网页、自制微信小程序等三种方法之一进行数据的展现。

主要展现：

1. 金钱收益或损失；
2. 关注的股票行情；
3. 情感分析的来源以及分析的结果评分；
4. 舆情分析的来源与分析的结果评分。

* 经费投入与导出设定

经费的投入原则是：不心疼。将不心疼的钱投进去。

世界上没有绝对的不心疼。所以制定两个原则进行投入投出：

1. 指数2原则。从某一初始值x0开始，每个周期内投入如下金钱： x_{投入}= \frac{1}{2}\cdot (x_{0}+ \Zelta x)。这种投入金钱的结果就是，如果损失很大，那么之后的投入就会很小，如果损失越来越大，那么投入将会越来越小。投入的变化将会遵循一个指数式的增长或者降低。同样地，在资金抽取里，也需要遵循这样的指数2原则：在计算完投入的金钱之后，需要计算要从投入的金钱里拿出多少。这里的拿出的金额仅仅和增量有关，也就是满足： x_{拿出}=\frac{1}{2}\cdot \Zelta x)*（\Zelta x >0）。 指数2原则保证了投资游戏的本钱只会越来越多，而永远不会变少。这个想法是大胆的、草率的、危险的。这种投入方法虽然会让我们不心疼，但是我们真的愿意把钱丢进火坑里么？

2. 神经网络决策原则。当我们确定了每一周期投入的钱荷投出的钱之后，另一个问题就是如何使用这些钱。此刻使用的就是神经网络决策原则。具体思路是：投入的钱不会直接被用来进行投资，而是被投放在一个储蓄池里，也就是成为神经网络可供操作的上限（这也是一个参数，一个输入变量），之后，神经网络自主决定要使用多少钱。而导出的钱，也不能直接进入使用者的腰包，而是被预留出来作为下一周期的投入，通过这种方式，可以设想几种局面：1）如果情况很好，很赚钱。那么收益的钱将转进到储蓄池里，替代掉一部分的投资，这样就可以减轻投资者的压力。但是很显然，无论什么时候，如果盈利，使用者都得往里面投钱。那么这个投资到底是吃人的钱的还是挣钱的呢？一会会讨论这种策略的正确性；2）如果情况很糟糕，入不敷出，亏了一些钱，这时会出现什么情况？对于拿出的钱，很显然已经变成0了。而对于投入的钱，其实仍然在源源不断地进场，全部都流动到了储蓄池里。当某个周期的亏损已经和初始的本金一样的时候，资金就会停止流入到储蓄池中。这个时候，已经投出去的钱可能还在亏损，或者通过某种方式进行流出，但是巨大的储蓄池却成了资金的一个容纳所，为日后的投资积攒资金准备。

下面看一下由于原则1带来的大问题：只进不出问题。这是进行利滚利的一个决策。也就是：只要赚钱，就默认还会赚钱，直到开始亏钱。但是亏钱的曲线总是下降的很快，所以必须有足够的舆情机制可以遏制住这个东西，不然危险的紧。第二个问题是：既然每个周期都要投入钱，那么投资的收益何在？我认为这个收入应该从储蓄池里抽走，如果储蓄池超过了一定水位，然后舆论分析认为行情一般或者不太好，那么就应该抽走资金。

* 学习计划

学习如何使用股票

学习量化投资

学习某某某东西。




