#+title: something.
#+author: liangzid.
#+date: some.


* 

他再也没有见过她，当他慌慌张张从座位上离开时，他便领悟到那是永别了。

“张难！”

未及屏幕上滚动出他的名字，大嗓门就把他吓得跑了上去。

“坐在这里。对，来，看着摄像头。”那人把他的身份证拿过去扫了一下，旁边的打印机呼呼呼吐出一张纸，她连头也不抬，直接把那张纸拽到跟前，两个红戳子砸了上去，一切就都完成了。她还是操着那种大嗓门说：“喏，拿着它去小备考室，等着。”

应该再要一个联系方式的，他常常如此想。那时他坐在小备考室里，努力试图挺直脊梁骨，他摘下眼镜，想让眼睛放松下来，结果眩晕感反而乘势而起，他两肚空空，越发觉得难过。不要再想她啦！只不过是见了一面。考试要紧，考试要紧。

当然，最后，他不出意料地挂掉了。手脚之间困难的协调，驾控飞船所面临的巨大的不确定性，都成了他巨大的阻碍。他惶恐地看着四周，从太阳穴处延续出来的如同脉搏一般的眩晕感彻底让他无所适从了。

他不是没有吃东西，在座位上，他啃了半个她的面包。他讨厌吃面包，那东西对他而言太甜，每次咽下去嘴里都有一种致命的腻味。包子、韭菜盒子、烧饼他都能接受，可是面包对他而言就太难。可是他那时候饿的发晕，而她才考完试。所以他仍然感激她。当时的他很想通过这个契机加她的微信，当然，她机智地使用了微信的收款功能。

* 

等到回到家里，他才发现那真的是永别。考试失败的哀伤一哄而散，他知道自己可以重新再考，可是那个人他再也看不见了。他躺在床上，想补一觉，可是怎么也睡不着。他想到她的模样，这个时候她的面容就已经模糊起来了。他开始叹息，为什么不能吐露一些爱意呢？等待考试时，觉得唐突，而现在，却感觉太过保守。

他想细细分析自己为什么会喜欢她。没什么原因，或许是仅仅是因为她长得好看。她长得确实好看，虽然贴近眼睛处，可以看到一些斑点。他很伤心自己也是那种见色起意的男人。他不仅仅是那种见色起意的男人，还是那种爱撒谎的人。他不是第一次见她。在他练车的时候，他就已经见过她。离得非常远，但是能望见。当然，现在来看离得更远了。之前，他对她引起在意是因为她的名字，她的名字经常被一个同班同学提起过，他总觉得他熟知这个名字。但是，或许在她看来这样套用红楼梦的梗毫无意义吧。

他在那里思索，一边为自己不能再见到她伤心，一边为自己的考试失败伤心。可是无论怎么伤心，前者竟然渐渐把后者压倒了。他又发现微信上可以联系收款方，单方面的联系。他想试一试，可是他根本不知道要说什么。他不会和女生聊天。他只会和女生说和男生说的事，以及表白。如果他对她说那些和爱情无关的事，那么他为什么要加回他的好友呢？如果他要表白，是不是过于唐突了呢？

他想到这里的时候，就开始幻想和她在一起的日子了。他有点羞于让周围一起学车的人发现这件事，他觉得非常尴尬。他很熟悉这个情节，那是四年前，他鼓起勇气第一次给一个女孩告白。他什么也不知道，甚至连她在谈恋爱都不知道。多么可悲，他竟然就这样表白了。结果可想而知，他和她三年没有见过面。

那次表白和这次何其相似！考试滑铁卢，表白，被拒，考试滑铁卢。回忆的滚滚车轮倾轧着他前行。他甚至编好了一个借口，“我的雨伞找不到了，你看见了吗？”这个借口太流俗了。并且是绝对的不诚信。他又想过写小说。他对自己的小说已经失望了，经过一次又一次投稿之后。他早就失去了灵感，失去了所有的灵感。可是他还是想试图动笔写几个字，然后发给她。他第一次遇到一见钟情的事，他又一次喜欢上了一个人。他不想就这样让仅有的相见变成永别。

可是他根本就写不出来什么。无奈之下，他只能编造了一个科幻背景下考取飞船驾照的故事，然后发给她让她看。他一开始写的一本正经，后来却越来越不着调，再往后完全都是干巴巴的心理描写了。他越写越惶恐，键盘敲个不停，他知道这么长的文字肯定超出了150字，或许她看完第一行就丢掉这整篇文章了。他怕她看不出他的莫名其妙的“喜欢”，又怕她真的看清。总之，啰里啰唆，那篇文章就这样写完了。








