#+ title: 存在与时间基本笔记

* 引言
这几日在忙毕设答辩的事情，加上又要学出来一张驾驶证，东忙西忙里，读书变成了一种消遣的活动，因而那些需要很动脑子的书便搁置下来了。
今日父母在家，省下了我做饭的工夫，坐在书桌前无聊，又翻了翻上周在读的一本书，发现人的脑子总是会很快丢掉一些东西。出于一种留恋，我想把那些要忘掉的东西写下来，留待后来的自己耻笑。
我想先从《存在与时间》这本书开始。或许后来的很多带有“功用”性质的书籍都会获得这种待遇，甚至这类感悟会推广到自己读过的一些小说上。这些都说不准，因而只有先把手头的东西写一写了。
仍然需要声明：这些东西都是一些个人向的、暂时的想法，作者在谈及这些想法时不免是十分幼稚的，因此可以接受任何形式的探讨和批评，虽然很不爽。

** 对一般文本的普遍特质的思索
在进行对《存在与时间》这本书的讨论之前，我想先表明目前在我阅读一本书时进行评判的几个维度，以便为以后所有书籍的评判给出一个先天的探索角度。一篇文章，无论它是好是坏，里面都包含着某些“东西”。（这是废话。）文字作为人类语言的一种载体，它几乎可以承担一个人想象的所有内容。无论是一些故事，还是一些说理论道的东西，都可以囊括在里面。从这个角度出发，文本总是会包含这些特质：1）文本必须是描述性质的。也就是，它必须做到“言之有物”，它必须讲某个东西。这个东西可以是真实的也可以是虚无的也可以是讲述文本本身，但是它必须要有。如果，某个人开发了一个软件，会从新华字典里随机选取一个字出来，这样不断地添加添加形成一篇文章，并随机地输入一些分隔的标点符号。这篇文章，这样的结果，可以算做是一篇文本吗？我的回答是，有可能可以。因为评判“字的组合”是否是一个文本的并不是这个文本如何产生，而是读者能否从中捕获到什么意义。从这个角度看，我对“一般文本”这个概念的定义可谓是特别主观了。
是的，我认同这种主观性。一个没学过中文的外国人，当他阅读我用中文写的一本非常下流的黄色小说时，他肯定没什么生理反应。这个例子不太恰当，还是拿画做比喻，某个抽象派大师画了一部非常厉害的神画，可是我并不懂如何欣赏绘画，所以我觉得这画和我幼儿园做的一些区别在何处。对于我而言，那幅画并不能算得上是一幅画，因为我“无可捕捉，无可沉浸”。很多时候文本也是会存在这一现象的。
幸运的是，文本在这一方面的进展显然没有像绘画那么极端，有人说可能是受限于语法，可是早在艾略特的现代诗时代，语法的松绑就开始有人跃跃欲试了，虽然效果一般。（突然想起来，现代诗算是文学赏析里一个独特的难点。）总之，文本必须言之有物，这个观点与其说是给出了文本的性质，不如说是定义了文本。2）在描述性质的基础上，文本必须通过这样或者那样的方式展示它所描述的东西。这句话当然也是废话，并且“箭头”的方向还很可能倒置了。这个方面倒是促进了文学作为一种艺术的诞生。什么是艺术？术，是一种方法，一类套路的综合。而艺，是一个“巧妙的”、“有趣的”、带有一定“卖弄”意义的、让人眼前一亮的、观赏性强的、除非你练过否则一般人上手不行——这样一些“手段”的统称。所以，作为一种艺术的文学，就要在以上的那些形容词上有所展示。文学就是在这种背景下产生的，我要去表达一个东西，我要去描述一个东西，当一个人着重于他们表达的那些“东西”的时候，这个作品的灵魂在那些东西上，也就成了某些学科里的名著；当一个人确确实实表达了一些东西，但是将重点放在“我怎么去表达或者描述这些东西”的时候，他就开始思索文学。这样的作品，才能登堂入室成为“艺术”上的文学作品。当然，这两个方向并不矛盾，论道性质的《论语》、《庄子》，文学欣赏起来也很不错，这当然和中国的哲学思想有关。西方虽然也存在很多这种“二者兼顾
的东西（比如那个康德很喜欢的《爱弥儿》），但是他们的特质使得他们对这个东西分得很开很开，这是好事也是坏事，比如现在的我在写这篇文章，一篇除非你在思索这些观点否则毫无美感的文章，显然是收到西方的影响了。在此处，我还要稍微歇息一下，讨论一下“如何描述”与“描述什么”之间的关联问题。很多人都不止一次地给我说，文学的价值不在于内容而在于形式，从而劝诫我少走弯路。这句话听起来总是有道理的。很早之前就有人说，故事就那么多类，早已被人讲尽啦。所以，当面对金庸、大仲马这些人的通俗小说时，人们总觉得他们对文学并无太大贡献。我自然理解这些观点，也无意为这些人辩驳。辩驳也是不必要的，人们就是喜欢那些故事，而不是那些“哲学精神”或者“手法”。此处想探究的，是形式与内容之间的关联。比如，给你一块肉（我们不去讨论这肉是猪肉还是羊肉）和一些佐料，让你做出一点食物来。这里的食材就很像是那些原料，而作家的高明之处就在于他们烹饪的方法。（当然，写作和做饭大有不同。这个类比同样不是特别合适。）烹饪的方法？他们烹饪的方法也许并不好吃（你看，这又是个主观问题），但是，如果他们发明了一种新的方法（比如烧烤的时候撒点孜然面），他们估计就会出名。但是烤出来的肉一定比红烧的好吃吗？这不一定啊，并且也没人在乎。形式和内容就是这样交融在一起的，很多评论的人都是在阅读文本时，尝试从里面挑出一些手法，然后进行分析。这是应该的，但是，更应该的是，你先沉浸在文字里，感受完这个故事，之后才能回过头来一点点思索。手法也是这样，某个方法不适用于所有的内容，某种方法以某种程度与某种内容结合，这样才能完成一种艺术。假如有个人看着碟里的豆腐，还未动筷仅仅闻到了味道就破口大骂：“这也太臭了！为什么这么多人还爱吃？”假如这个人任凭别人夸赞其美味也毫不动心，只认同自己的鼻子，那么他的舌头又怎么知道臭豆腐的味道呢？同样地，还有一些人，他们总以为鸡蛋任谁煎都是鸡蛋，吃了媳妇炒的，便以为味道比全天下的大厨差不了太多。如果单纯是在一个鸡蛋上这么理论当然合适，但是，当食材越来越多，规模越来越大，事情就渐渐变了味道。当一个人读了一些简介、看了一些电视剧，就觉得自己已经品尝到长篇小说的滋味时，总有些东西我同他说不清楚。当然，一个东西可以通过多种媒介表达，如果你想通过文字表达，并且你还不了解文字区别于影视等媒介的区别，那么是不是同样有些说不过去呢？总之，文本必须通过某种东西表现，当此处的“某种东西”成了主角，这样的文本就容易上升为艺术了。

这两点是我所认为的一般特质，当一个文本被归纳成某些类，就会多出一些特质，比如虚构类的具有一些特质，非虚构类的具有一些等等。（暂不去考虑这种分类是否武断。）由于本文是一个引言性质的文章，因此我想接着就“非虚构性”进行一种讨论。

** 论“载道”的文的艺术性
先解一下题目。所谓“载道”的文，仅仅是说那些想表达一些思想的文章或书籍。比如，谈论某种哲学，谈论政治，谈论某领域的某个学说，或者发表对以上三种东西的一种评论。比如本文，虽然这个“道”不太有道理，但也是一篇“载道”的文章。中国古代，除了那些史书、诗词歌赋、小说，其他的东西多归于此类。在中国传统的文学里，这类东西没有一个不具有美感。这种风俗延续到了民国，比如闻一多等人的评论，仍然带着一股“文艺”的味道。而以我读西方的一些哲学书的感觉，他们在这方面显得更加纯粹一些，载道的就是载道的。后来，从民国到当代，我读到一些新的此类“载道”的文渐渐也失去了过去的那种艺术性，而彻底变成论道的东西了，这是好事也不是好事。

孔子对这种东西有过一个中庸的态度，或许可以作为一种思路：“质胜文则野，文胜质则史。”但是，鉴于目前社会里大家都不喜欢儒家，以及当代社会最喜欢激烈、走极端的样子，所谓“文质彬彬”的君子风怕是一去不复返啦。不过，同样地，仅仅通过孔老夫子的一句话可没办法把这个问题彻底说清楚。








